parameters:
#    hello_world.example.class: Hello\WorldBundle\Example

services:
#    hello_world.example:
#        class: %hello_world.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
